import { useState } from "react";
import {
  Pill, FlaskConical, Settings, FileSearch,
  ChevronUp, ChevronDown, Copy, Check, Printer, Eye,
  ActivitySquare, Thermometer, Heart, Wind, ClipboardList
} from "lucide-react";

const PRESCRIPTION_TABS = [
  { key: "drugs", label: "Drugs", icon: Pill, color: "var(--color-drugs)" },
  { key: "lab", label: "Lab-Test", icon: FlaskConical, color: "var(--color-lab)" },
  { key: "services", label: "Service", icon: Settings, color: "var(--color-services)" },
  { key: "findings", label: "Care-Plan", icon: FileSearch, color: "var(--color-info)" },
  { key: "timeline", label: "IP Timeline", icon: ClipboardList, color: "#d97706" },
];

// Function to calculate dosage schedule based on period
function getDosageSchedule(period, intake) {
  const schedules = {
    "OD": { mor: "", noon: "", eve: "", night: intake },
    "BD": { mor: intake, noon: "", eve: "", night: intake },
    "TDS": { mor: intake, noon: intake, eve: "", night: intake },
    "QID": { mor: intake, noon: intake, eve: intake, night: intake },
    "HS": { mor: "", noon: "", eve: "", night: intake },
    "SOS": { mor: "", noon: "", eve: "", night: "As needed" },
    "Stat": { mor: "", noon: "", eve: "", night: "Stat" },
    "Weekly": { mor: "", noon: "", eve: "", night: "Weekly" },
    "Monthly": { mor: "", noon: "", eve: "", night: "Monthly" }
  };
  return schedules[period] || schedules["OD"];
}

// Function to calculate total quantity (Buy)
function calculateBuy(days, intake, period) {
  const dosageCount = {
    "OD": 1, "BD": 2, "TDS": 3, "QID": 4, "HS": 1,
    "SOS": 1, "Stat": 1, "Weekly": 1, "Monthly": 1
  };
  
  let intakeNum = 1;
  if (intake.includes("½")) intakeNum = 0.5;
  else if (intake.includes("¼")) intakeNum = 0.25;
  else if (intake.includes("¾")) intakeNum = 0.75;
  else if (intake.includes("1½")) intakeNum = 1.5;
  else if (intake.includes("2")) intakeNum = 2;
  else if (intake.includes("3")) intakeNum = 3;
  else if (intake.includes("4")) intakeNum = 4;
  else if (!isNaN(parseFloat(intake))) intakeNum = parseFloat(intake);
  
  const dailyDosage = (dosageCount[period] || 1) * intakeNum;
  const total = Math.ceil((parseInt(days) || 1) * dailyDosage);
  return total;
}

// Helper to format intake display
function formatIntakeDisplay(intake, period, detail) {
  let display = `[${intake}`;
  if (period === "HS") display += `, Bedtime`;
  else if (period === "SOS") display += `, As needed`;
  else display += `, ${period}`;
  if (detail && detail !== "—") display += `, ${detail}`;
  display += `]`;
  return display;
}

// Format prescription data for copying
function formatPrescriptionForCopy(visit, prescriptions) {
  let text = `MEDIX - PRESCRIPTION\n`;
  text += `${"=".repeat(50)}\n\n`;
  text += `Visit Date: ${visit.entryDt}\n`;
  text += `Doctor: ${visit.by}\n`;
  text += `Module: ${visit.docModule}\n`;
  text += `Chief Complaint: ${visit.complaint}\n\n`;
  
  // Drugs
  if (prescriptions.drugs?.length > 0) {
    text += `DRUGS:\n`;
    text += `S.No | Drug | Buy | Mor | Noon | Eve | Night | When | Detail\n`;
    text += `${"-".repeat(70)}\n`;
    prescriptions.drugs.forEach((drug, i) => {
      const schedule = getDosageSchedule(drug.period, drug.intake);
      const buy = calculateBuy(drug.days, drug.intake, drug.period);
      text += `${i + 1} | ${drug.name} | ${buy} | ${schedule.mor || '-'} | ${schedule.noon || '-'} | ${schedule.eve || '-'} | ${schedule.night || '-'} | ${drug.when} | ${drug.detail}\n`;
    });
    text += `\n`;
  }
  
  // Labs
  if (prescriptions.labs?.length > 0) {
    text += `LAB TESTS:\n`;
    prescriptions.labs.forEach((lab, i) => {
      text += `${i + 1}. ${lab.name} - ${lab.detail}\n`;
    });
    text += `\n`;
  }
  
  // Services
  if (prescriptions.services?.length > 0) {
    text += `SERVICES:\n`;
    prescriptions.services.forEach((service, i) => {
      text += `${i + 1}. ${service.type} - ${service.name} (${service.detail})\n`;
    });
    text += `\n`;
  }
  
  // Findings
  if (prescriptions.findings && Object.keys(prescriptions.findings).length > 0) {
    text += `CLINICAL FINDINGS:\n`;
    if (prescriptions.findings.diagnosis) text += `Diagnosis: ${prescriptions.findings.diagnosis}\n`;
    if (prescriptions.findings.clinicalNotes) text += `Notes: ${prescriptions.findings.clinicalNotes}\n`;
    if (prescriptions.findings.advice) text += `Advice: ${prescriptions.findings.advice}\n`;
    if (prescriptions.findings.nextVisit) text += `Next Visit: ${prescriptions.findings.nextVisit}\n`;
  }
  
  text += `\n${"=".repeat(50)}\n`;
  text += `Generated by Medix Healthcare Platform\n`;
  return text;
}

// Render Drugs Tab Content
function DrugsTabContent({ prescriptions }) {
  const drugs = prescriptions?.drugs || [];
  if (drugs.length === 0) {
    return (
      <div className="text-center py-8">
        <Pill size={32} style={{ color: "var(--color-text-subtle)" }} />
        <p className="text-sm mt-2" style={{ color: "var(--color-text-muted)" }}>No drugs prescribed</p>
      </div>
    );
  }
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr style={{ background: "var(--color-primary-muted)" }}>
            <th className="px-2 py-2 text-center w-12">S.No</th>
            <th className="px-2 py-2 text-left">Drug</th>
            <th className="px-2 py-2 text-center w-12">Buy</th>
            <th className="px-2 py-2 text-center w-12">Mor</th>
            <th className="px-2 py-2 text-center w-12">Noon</th>
            <th className="px-2 py-2 text-center w-12">Eve</th>
            <th className="px-2 py-2 text-center w-12">Night</th>
            <th className="px-2 py-2 text-center w-20">When</th>
            <th className="px-2 py-2 text-left w-28">Detail</th>
          </tr>
        </thead>
        <tbody>
          {drugs.map((drug, idx) => {
            const schedule = getDosageSchedule(drug.period, drug.intake);
            const buy = calculateBuy(drug.days, drug.intake, drug.period);
            const intakeDisplay = formatIntakeDisplay(drug.intake, drug.period, drug.detail);
            
            return (
              <tr key={idx} className="border-b" style={{ borderColor: "var(--color-border)" }}>
                <td className="px-2 py-2 text-center font-semibold" style={{ color: "var(--color-primary)" }}>
                  {idx + 1}
                </td>
                <td className="px-2 py-2">
                  <div className="font-semibold text-sm">{drug.name}</div>
                  <div className="text-[0.6rem]" style={{ color: "var(--color-text-subtle)" }}>
                    {intakeDisplay}
                  </div>
                </td>
                <td className="px-2 py-2 text-center font-bold" style={{ color: "var(--color-drugs)" }}>
                  {buy}
                </td>
                <td className="px-2 py-2 text-center">{schedule.mor}</td>
                <td className="px-2 py-2 text-center">{schedule.noon}</td>
                <td className="px-2 py-2 text-center">{schedule.eve}</td>
                <td className="px-2 py-2 text-center">{schedule.night}</td>
                <td className="px-2 py-2 text-center text-xs">{drug.when}</td>
                <td className="px-2 py-2 text-xs" style={{ color: "var(--color-text-muted)" }}>
                  {drug.detail === "—" ? "" : drug.detail}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// Render Labs Tab Content
function LabsTabContent({ prescriptions }) {
  const labs = prescriptions?.labs || [];
  if (labs.length === 0) {
    return (
      <div className="text-center py-8">
        <FlaskConical size={32} style={{ color: "var(--color-text-subtle)" }} />
        <p className="text-sm mt-2" style={{ color: "var(--color-text-muted)" }}>No lab tests ordered</p>
      </div>
    );
  }
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr style={{ background: "var(--color-lab-light)" }}>
            <th className="px-3 py-2 text-left">Test Name</th>
            <th className="px-3 py-2 text-left">Instructions</th>
          </tr>
        </thead>
        <tbody>
          {labs.map((lab, idx) => (
            <tr key={idx} className="border-b" style={{ borderColor: "var(--color-border)" }}>
              <td className="px-3 py-2 font-semibold">{lab.name}</td>
              <td className="px-3 py-2 text-xs" style={{ color: "var(--color-text-muted)" }}>{lab.detail === "—" ? "" : lab.detail}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render Services Tab Content
function ServicesTabContent({ prescriptions }) {
  const services = prescriptions?.services || [];
  if (services.length === 0) {
    return (
      <div className="text-center py-8">
        <Settings size={32} style={{ color: "var(--color-text-subtle)" }} />
        <p className="text-sm mt-2" style={{ color: "var(--color-text-muted)" }}>No services ordered</p>
      </div>
    );
  }
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm">
        <thead>
          <tr style={{ background: "var(--color-services-light)" }}>
            <th className="px-3 py-2 text-left">Type</th>
            <th className="px-3 py-2 text-left">Service Name</th>
            <th className="px-3 py-2 text-left">Body Part / Details</th>
          </tr>
        </thead>
        <tbody>
          {services.map((service, idx) => (
            <tr key={idx} className="border-b" style={{ borderColor: "var(--color-border)" }}>
              <td className="px-3 py-2">
                <span className="inline-flex px-2 py-0.5 rounded text-xs font-semibold" style={{ background: "var(--color-services-light)", color: "var(--color-services)" }}>
                  {service.type}
                </span>
              </td>
              <td className="px-3 py-2 font-semibold">{service.name}</td>
              <td className="px-3 py-2 text-xs" style={{ color: "var(--color-text-muted)" }}>{service.detail === "—" ? "" : service.detail}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// Render Findings Tab Content
function FindingsTabContent({ prescriptions }) {
  const findings = prescriptions?.findings;
  if (!findings || Object.keys(findings).length === 0 || !findings.diagnosis && !findings.clinicalNotes && !findings.advice) {
    return (
      <div className="text-center py-8">
        <FileSearch size={32} style={{ color: "var(--color-text-subtle)" }} />
        <p className="text-sm mt-2" style={{ color: "var(--color-text-muted)" }}>No clinical findings recorded</p>
      </div>
    );
  }
  return (
    <div className="space-y-4">
      {findings.diagnosis && (
        <div className="p-3 rounded-lg border" style={{ borderColor: "var(--color-border)" }}>
          <div className="text-xs font-bold uppercase mb-1" style={{ color: "var(--color-text-muted)" }}>Diagnosis</div>
          <div className="text-sm">{findings.diagnosis}</div>
        </div>
      )}
      {findings.clinicalNotes && (
        <div className="p-3 rounded-lg border" style={{ borderColor: "var(--color-border)" }}>
          <div className="text-xs font-bold uppercase mb-1" style={{ color: "var(--color-text-muted)" }}>Clinical Notes</div>
          <div className="text-sm">{findings.clinicalNotes}</div>
        </div>
      )}
      {findings.advice && (
        <div className="p-3 rounded-lg border" style={{ borderColor: "var(--color-border)" }}>
          <div className="text-xs font-bold uppercase mb-1" style={{ color: "var(--color-text-muted)" }}>Advice</div>
          <div className="text-sm">{findings.advice}</div>
        </div>
      )}
      {findings.nextVisit && (
        <div className="p-3 rounded-lg border" style={{ borderColor: "var(--color-border)" }}>
          <div className="text-xs font-bold uppercase mb-1" style={{ color: "var(--color-text-muted)" }}>Next Visit</div>
          <div className="text-sm">{findings.nextVisit}</div>
        </div>
      )}
      {findings.referTo && (
        <div className="p-3 rounded-lg border" style={{ borderColor: "var(--color-border)" }}>
          <div className="text-xs font-bold uppercase mb-1" style={{ color: "var(--color-text-muted)" }}>Refer To</div>
          <div className="text-sm">{findings.referTo}</div>
        </div>
      )}
      {findings.followupNote && (
        <div className="p-3 rounded-lg border" style={{ borderColor: "var(--color-border)" }}>
          <div className="text-xs font-bold uppercase mb-1" style={{ color: "var(--color-text-muted)" }}>Follow-up Note</div>
          <div className="text-sm">{findings.followupNote}</div>
        </div>
      )}
    </div>
  );
}

export default function PrescriptionViewModal({ 
  visit, 
  prescriptions, 
  onClose,
  onClear,
  onNavigate,
  currentIndex,
  totalVisits
}) {
  const [activeTab, setActiveTab] = useState("drugs");
  const [copied, setCopied] = useState(false);
  
  if (!visit) return null;

  const handleCopy = async () => {
    const textToCopy = formatPrescriptionForCopy(visit, prescriptions);
    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy: ', err);
    }
  };

  const handleProto = () => {
    alert("Proto feature coming soon!");
  };

  const handlePrint = () => {
    window.print();
  };

  const handlePreview = () => {
    alert("Preview feature coming soon!");
  };

  const handleCancel = () => {
    if (onClear) {
      onClear();
    }
    onClose();
  };

  const isParked = () => {
    const parkedSlNos = [44, 42, 40];
    return parkedSlNos.includes(visit.sl);
  };

  const handlePrevious = () => {
    if (onNavigate && currentIndex > 0) {
      onNavigate(currentIndex - 1);
    }
  };

  const handleNext = () => {
    if (onNavigate && currentIndex < totalVisits - 1) {
      onNavigate(currentIndex + 1);
    }
  };

  // Extract vitals and clinical data from visit
  const vitalsData = {
    bp: visit.vitals ? visit.vitals.split('/')[3] + '/' + visit.vitals.split('/')[4] : "—",
    temp: visit.vitals ? visit.vitals.split('/')[1] : "—",
    pulse: visit.vitals ? visit.vitals.split('/')[5] : "—",
    spo2: visit.vitals ? visit.vitals.split('/')[6] : "—",
    height: visit.height || "—",
    weight: visit.weight || "—",
  };

  const clinicalData = {
    chiefComplaint: visit.complaint || "—",
    firstObservation: visit.observation || "—",
    pregnancy: visit.pregnancy || "—",
    referral: visit.referral || "—",
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center" style={{ background: "rgba(0,0,0,0.5)" }}>
      <div className="rounded-xl overflow-hidden shadow-2xl" style={{ background: "var(--color-surface)", width: "950px", height: "80vh", display: "flex", flexDirection: "column" }}>
        
        {/* Header with Navigation and Actions */}
        <div className="px-4 py-3 flex justify-between items-center flex-shrink-0" style={{ background: "var(--color-primary)", color: "white" }}>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <span className="text-sm font-bold">Visit Details - SL No: {visit.sl}</span>
              <span className="text-xs ml-1 opacity-80">{visit.entryDt}</span>
              
              {isParked() && (
                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[0.6rem] font-semibold ml-2"
                  style={{ background: "#fef3c7", color: "#d97706" }}>
                  <ParkingCircle size={10} />
                  Parked
                </span>
              )}
            </div>
            
            <div className="flex items-center gap-1 ml-4">
              <button
                onClick={handlePrevious}
                disabled={currentIndex === 0}
                className="p-1 rounded transition-all hover:bg-white/20 disabled:opacity-30 disabled:cursor-not-allowed"
                title="Previous Visit"
              >
                <ChevronUp size={16} />
              </button>
              <button
                onClick={handleNext}
                disabled={currentIndex === totalVisits - 1}
                className="p-1 rounded transition-all hover:bg-white/20 disabled:opacity-30 disabled:cursor-not-allowed"
                title="Next Visit"
              >
                <ChevronDown size={16} />
              </button>
              <span className="text-xs ml-1 opacity-80">
                {currentIndex + 1} / {totalVisits}
              </span>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <button onClick={handleProto} className="p-1 rounded transition-all hover:bg-white/20 flex items-center gap-1">
              <BookOpen size={14} />
              <span className="text-xs">Proto</span>
            </button>
            <button onClick={handlePrint} className="p-1 rounded transition-all hover:bg-white/20 flex items-center gap-1">
              <Printer size={14} />
              <span className="text-xs">Print</span>
            </button>
            <button onClick={handlePreview} className="p-1 rounded transition-all hover:bg-white/20 flex items-center gap-1">
              <Eye size={14} />
              <span className="text-xs">Preview</span>
            </button>
            <button onClick={handleCopy} className="p-1 rounded transition-all hover:bg-white/20 flex items-center gap-1">
              {copied ? <Check size={14} /> : <Copy size={14} />}
              <span className="text-xs">{copied ? "Copied!" : "Copy"}</span>
            </button>
            <button onClick={handleCancel} className="p-1 rounded transition-all hover:bg-white/20 flex items-center gap-1">
              <Ban size={14} />
              <span className="text-xs">Cancel</span>
            </button>
          </div>
        </div>
        
        {/* Visit Info Summary with Vital Signs (Left) and Clinical Information (Right) */}
        <div className="px-4 py-3 border-b flex-shrink-0" style={{ borderColor: "var(--color-border)", background: "var(--color-surface-alt)" }}>
          {/* Top Row: Doctor, Module, Report Date, Next Visit */}
          <div className="grid grid-cols-2 gap-3 text-xs">
            <div>
              <span className="font-bold" style={{ color: "var(--color-text-muted)" }}>Doctor:</span>
              <span className="ml-1">{visit.by}</span>
            </div>
            <div>
              <span className="font-bold" style={{ color: "var(--color-text-muted)" }}>Module:</span>
              <span className="ml-1">{visit.docModule}</span>
            </div>
            <div>
              <span className="font-bold" style={{ color: "var(--color-text-muted)" }}>Report Date:</span>
              <span className="ml-1">{visit.reportDt || "—"}</span>
            </div>
            <div>
              <span className="font-bold" style={{ color: "var(--color-text-muted)" }}>Next Visit:</span>
              <span className="ml-1" style={{ color: visit.nextVisit ? "var(--color-success)" : "inherit" }}>{visit.nextVisit || "—"}</span>
            </div>
          </div>
          
          {/* Chief Complaint */}
          <div className="mt-2">
            <span className="font-bold text-xs" style={{ color: "var(--color-text-muted)" }}>Chief Complaint:</span>
            <span className="text-xs ml-1">{visit.complaint}</span>
          </div>
          
          {/* Bottom Row: Vital Signs (Left) | Clinical Information (Right) */}
          <div className="mt-2 pt-2 border-t grid grid-cols-2 gap-4" style={{ borderColor: "var(--color-border)" }}>
            {/* Left: Vital Signs */}
            <div>
              <div className="flex items-center gap-1.5 mb-1.5">
                <ActivitySquare size={12} style={{ color: "var(--color-primary)" }} />
                <span className="text-[0.55rem] font-bold tracking-wide" style={{ color: "var(--color-text-muted)" }}>Vital Signs</span>
              </div>
              <div className="flex flex-wrap gap-1.5">
                <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "#ef444418", border: "1px solid #ef444435" }}>
                  <ActivitySquare size={10} style={{ color: "#ef4444" }} />
                  <span className="text-xs font-bold" style={{ color: "#ef4444" }}>{vitalsData.bp}</span>
                  <span className="text-[0.5rem]" style={{ color: "#ef4444" }}>BP</span>
                </div>
                <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "#f9731618", border: "1px solid #f9731635" }}>
                  <Thermometer size={10} style={{ color: "#f97316" }} />
                  <span className="text-xs font-bold" style={{ color: "#f97316" }}>{vitalsData.temp}</span>
                  <span className="text-[0.5rem]" style={{ color: "#f97316" }}>Temp</span>
                </div>
                <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "#6366f118", border: "1px solid #6366f135" }}>
                  <Heart size={10} style={{ color: "#6366f1" }} />
                  <span className="text-xs font-bold" style={{ color: "#6366f1" }}>{vitalsData.pulse}</span>
                  <span className="text-[0.5rem]" style={{ color: "#6366f1" }}>Pulse</span>
                </div>
                <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "#06b6d418", border: "1px solid #06b6d435" }}>
                  <Wind size={10} style={{ color: "#06b6d4" }} />
                  <span className="text-xs font-bold" style={{ color: "#06b6d4" }}>{vitalsData.spo2}</span>
                  <span className="text-[0.5rem]" style={{ color: "#06b6d4" }}>SpO₂</span>
                </div>
              </div>
            </div>
            
            {/* Right: Clinical Information */}
            <div>
              <div className="flex items-center gap-1.5 mb-1.5">
                <Clipboard size={12} style={{ color: "var(--color-primary)" }} />
                <span className="text-[0.8rem] font-bold tracking-wide" style={{ color: "var(--color-text-muted)" }}>Clinical Information</span>
              </div>
              <div className="flex flex-wrap gap-1.5">
                {clinicalData.chiefComplaint && clinicalData.chiefComplaint !== "—" && (
                  <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "var(--color-danger)18", border: "1px solid var(--color-danger)35" }}>
                    <Stethoscope size={10} style={{ color: "var(--color-danger)" }} />
                    <span className="text-xs font-bold" style={{ color: "var(--color-danger)" }}>{clinicalData.chiefComplaint}</span>
                  </div>
                )}
                {clinicalData.firstObservation && clinicalData.firstObservation !== "—" && (
                  <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "#0284c718", border: "1px solid #0284c735" }}>
                    <Eye size={10} style={{ color: "#0284c7" }} />
                    <span className="text-xs font-bold" style={{ color: "#0284c7" }}>{clinicalData.firstObservation}</span>
                  </div>
                )}
                {clinicalData.referral && clinicalData.referral !== "—" && (
                  <div className="flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: "#d9770618", border: "1px solid #d9770635" }}>
                    <ArrowRightLeft size={10} style={{ color: "#d97706" }} />
                    <span className="text-xs font-bold" style={{ color: "#d97706" }}>{clinicalData.referral}</span>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
        
        {/* Prescription Tabs */}
        <div className="flex border-b flex-shrink-0" style={{ borderColor: "var(--color-border)" }}>
          {PRESCRIPTION_TABS.map(tab => {
            const isActive = activeTab === tab.key;
            const Icon = tab.icon;
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className="flex items-center gap-1.5 px-4 py-2.5 text-xs font-semibold transition-all"
                style={{
                  borderBottom: isActive ? `2px solid ${tab.color}` : "2px solid transparent",
                  color: isActive ? tab.color : "var(--color-text-muted)",
                  background: isActive ? `${tab.color}10` : "transparent"
                }}
              >
                <Icon size={14} />
                {tab.label}
              </button>
            );
          })}
        </div>
        
        {/* Tab Content - Scrollable */}
        <div className="flex-1 overflow-y-auto p-4">
          {activeTab === "drugs" && <DrugsTabContent prescriptions={prescriptions} />}
          {activeTab === "lab" && <LabsTabContent prescriptions={prescriptions} />}
          {activeTab === "services" && <ServicesTabContent prescriptions={prescriptions} />}
          {activeTab === "findings" && <FindingsTabContent prescriptions={prescriptions} />}
        </div>
        
        {/* Footer */}
        <div className="px-4 py-3 border-t flex justify-end flex-shrink-0" style={{ borderColor: "var(--color-border)" }}>
          <button onClick={onClose} className="px-4 py-1.5 rounded-lg text-sm font-semibold transition-all"
            style={{ background: "var(--color-primary)", color: "white" }}
            onMouseEnter={(e) => e.currentTarget.style.background = "var(--color-primary-light)"}
            onMouseLeave={(e) => e.currentTarget.style.background = "var(--color-primary)"}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
